# Generated by Django 5.2.3 on 2025-08-20 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspensionPartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vin', models.CharField(blank=True, max_length=64)),
                ('vehicle_model', models.CharField(blank=True, max_length=128)),
                ('raw_file', models.FileField(upload_to='diagnostic_reports/')),
                ('recommendation', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('engine_done', 'Диагностика двигателя завершена'), ('suspension_pending', 'Ожидает осмотра подвески'), ('suspension_done', 'Диагностика подвески завершена')], default='engine_done', max_length=30)),
                ('handover_time', models.DateTimeField(blank=True, null=True)),
                ('suspension_comment', models.TextField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_known', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='diagnostics.diagnosticsession')),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(help_text='Время в секундах от начала записи')),
                ('name', models.CharField(max_length=64)),
                ('value', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='diagnostics.diagnosticsession')),
            ],
        ),
        migrations.CreateModel(
            name='SuspensionInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userprofile')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suspension', to='diagnostics.diagnosticsession')),
            ],
        ),
        migrations.CreateModel(
            name='SuspensionPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wear_percent', models.PositiveSmallIntegerField()),
                ('part_number', models.CharField(blank=True, max_length=64)),
                ('needs_replacement', models.BooleanField(default=False)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='diagnostics.suspensioninspection')),
                ('part_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='diagnostics.suspensionparttype')),
            ],
        ),
    ]
