# Generated by Django 5.2.3 on 2026-01-13 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0002_alter_suspensioninspection_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticsession',
            name='ai_disclaimer_version',
            field=models.CharField(blank=True, default='v1', max_length=32),
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='ai_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='expert_conclusion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='expert_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='expert_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='system_report',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='suspensioninspection',
            name='lift_used',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='suspensioninspection',
            name='mileage_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspensioninspection',
            name='overall_risk',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='suspensioninspection',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suspensioninspection',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('signed', 'Подписан мастером')], default='draft', max_length=16),
        ),
        migrations.AddField(
            model_name='suspensioninspection',
            name='test_drive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suspensionpart',
            name='evidence',
            field=models.TextField(blank=True, help_text='Наблюдения/замеры: что именно увидели/услышали/померили'),
        ),
        migrations.AddField(
            model_name='suspensionpart',
            name='reason',
            field=models.CharField(blank=True, help_text='Основание: люфт, трещины, потёк, стук, коррозия, деформация и т.п.', max_length=64),
        ),
        migrations.AddField(
            model_name='suspensionpart',
            name='severity',
            field=models.CharField(choices=[('ok', 'Ок'), ('warn', 'Внимание'), ('crit', 'Критично')], default='warn', max_length=8),
        ),
        migrations.CreateModel(
            name='SuspensionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='inspections/suspension/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='diagnostics.suspensioninspection')),
            ],
        ),
    ]
