# Generated by Django 5.2.3 on 2026-06-17 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0003_diagnosticsession_ai_disclaimer_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTCImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_created', models.PositiveIntegerField(default=0)),
                ('rows_updated', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Пакет импорта DTC',
                'verbose_name_plural': 'Пакеты импорта DTC',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OBDLiveDataPIDReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=20, unique=True)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('diagnostic_value', models.TextField(blank=True, help_text='Чем этот PID полезен при диагностике.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Справочник PID Live Data',
                'verbose_name_plural': 'Справочник PID Live Data',
                'ordering': ['pid'],
            },
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
            ],
            options={
                'verbose_name': 'Марка автомобиля',
                'verbose_name_plural': 'Марки автомобилей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DTCReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12)),
                ('system', models.CharField(choices=[('P', 'Powertrain'), ('C', 'Chassis'), ('B', 'Body'), ('U', 'Network')], db_index=True, max_length=1)),
                ('scope', models.CharField(choices=[('generic', 'Generic OBD-II'), ('manufacturer', 'Manufacturer-specific'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=32)),
                ('manufacturer', models.CharField(blank=True, default='', help_text='Пусто для generic OBD-II. Для бренд-специфичных кодов — Toyota, BMW, Hyundai и т.п.', max_length=120)),
                ('title_ru', models.CharField(blank=True, max_length=500)),
                ('title_en', models.CharField(blank=True, max_length=500)),
                ('description_ru', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('possible_causes', models.TextField(blank=True)),
                ('diagnostic_notes', models.TextField(blank=True)),
                ('recommended_checks', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('info', 'Информационный'), ('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=32)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('import_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dtc_references', to='diagnostics.dtcimportbatch')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dtc_references', to='diagnostics.vehiclebrand')),
            ],
            options={
                'verbose_name': 'Справочник DTC',
                'verbose_name_plural': 'Справочник DTC',
                'ordering': ['code', 'manufacturer'],
            },
        ),
        migrations.AddField(
            model_name='diagnosticcode',
            name='reference',
            field=models.ForeignKey(blank=True, help_text='Связь с глобальным справочником DTC.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_codes', to='diagnostics.dtcreference'),
        ),
        migrations.AddIndex(
            model_name='dtcreference',
            index=models.Index(fields=['code'], name='diagnostics_code_31737b_idx'),
        ),
        migrations.AddIndex(
            model_name='dtcreference',
            index=models.Index(fields=['system', 'scope'], name='diagnostics_system_da242a_idx'),
        ),
        migrations.AddIndex(
            model_name='dtcreference',
            index=models.Index(fields=['manufacturer'], name='diagnostics_manufac_62d073_idx'),
        ),
        migrations.AddConstraint(
            model_name='dtcreference',
            constraint=models.UniqueConstraint(fields=('code', 'manufacturer'), name='unique_dtc_reference_per_manufacturer'),
        ),
    ]
