# Generated by Django 5.2.3 on 2026-06-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0004_dtcimportbatch_obdlivedatapidreference_vehiclebrand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticcode',
            name='module_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='diagnosticcode',
            name='module_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='diagnosticcode',
            name='raw_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diagnosticcode',
            name='status_text',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='diagnosticcode',
            name='code',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='diagnosticcode',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='dtcreference',
            name='code',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='dtcreference',
            name='scope',
            field=models.CharField(choices=[('generic', 'Универсальный OBD-II'), ('manufacturer', 'Бренд-специфичный'), ('unknown', 'Неизвестно')], db_index=True, default='unknown', max_length=32),
        ),
        migrations.AlterField(
            model_name='dtcreference',
            name='system',
            field=models.CharField(choices=[('P', 'Двигатель / трансмиссия'), ('C', 'Ходовая часть'), ('B', 'Кузовная электроника'), ('U', 'Сеть / CAN'), ('O', 'OEM / заводской код')], db_index=True, max_length=1),
        ),
    ]
