# Generated by Django 5.2.3 on 2026-08-16 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0005_diagnosticcode_module_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticsession',
            name='analysis_engine',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='analysis_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='analysis_method',
            field=models.CharField(blank=True, choices=[('rules', 'Правила'), ('knowledge_base', 'База знаний'), ('llm', 'Языковая модель'), ('hybrid', 'Гибридный анализ')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='analysis_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='DiagnosticParseRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(default='launch_pdf', max_length=32)),
                ('parser_name', models.CharField(max_length=64)),
                ('parser_version', models.CharField(max_length=32)),
                ('content_sha256', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('succeeded', 'Успешно'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=16)),
                ('is_current', models.BooleanField(db_index=True, default=False)),
                ('parsed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('fault_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parse_runs', to='diagnostics.diagnosticsession')),
            ],
            options={
                'verbose_name': 'Запуск парсера диагностики',
                'verbose_name_plural': 'Запуски парсера диагностики',
                'ordering': ['-parsed_at'],
            },
        ),
        migrations.AddField(
            model_name='diagnosticcode',
            name='parse_run',
            field=models.ForeignKey(blank=True, help_text='Запуск парсера, создавший это наблюдение.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_observations', to='diagnostics.diagnosticparserun'),
        ),
        migrations.AddIndex(
            model_name='diagnosticparserun',
            index=models.Index(fields=['session', 'status'], name='diagnostics_session_c00e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticparserun',
            index=models.Index(fields=['parser_name', 'parser_version'], name='diagnostics_parser__6111ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='diagnosticparserun',
            constraint=models.UniqueConstraint(fields=('session', 'parser_name', 'parser_version', 'content_sha256'), name='unique_parse_run_per_session_parser_content'),
        ),
        migrations.AddConstraint(
            model_name='diagnosticparserun',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('session',), name='unique_current_parse_run_per_session'),
        ),
    ]
