# Generated by Django 5.2.3 on 2026-08-16 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0006_diagnosticsession_analysis_engine_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16)),
                ('summary', models.TextField(blank=True)),
                ('confirmed_cause', models.TextField(blank=True)),
                ('recommended_work', models.TextField(blank=True)),
                ('safety_notes', models.TextField(blank=True)),
                ('content_sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_diagnostic_records', to='users.userprofile')),
                ('previous_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='diagnostics.diagnosticrecord')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='diagnostics.diagnosticsession')),
            ],
            options={
                'ordering': ['session_id', '-revision'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('value_text', models.CharField(blank=True, max_length=255)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('reference_min', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('reference_max', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('result', models.CharField(choices=[('normal', 'Normal'), ('out_of_range', 'Out of range'), ('not_evaluated', 'Not evaluated')], default='not_evaluated', max_length=20)),
                ('method', models.CharField(blank=True, max_length=255)),
                ('tool_name', models.CharField(blank=True, max_length=255)),
                ('evidence_note', models.TextField(blank=True)),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('measured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_measurements', to='users.userprofile')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='measurements', to='diagnostics.diagnosticrecord')),
            ],
            options={
                'ordering': ['measured_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('request_changes', 'Request changes')], max_length=24)),
                ('comment', models.TextField(blank=True)),
                ('snapshot_sha256', models.CharField(max_length=64)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_approvals', to='users.userprofile')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approvals', to='diagnostics.diagnosticrecord')),
            ],
            options={
                'ordering': ['decided_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QAEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='warning', max_length=16)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qa_events', to='diagnostics.diagnosticrecord')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_qa_events', to='users.userprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qa_events', to='diagnostics.diagnosticsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='diagnosticrecord',
            constraint=models.UniqueConstraint(fields=('session', 'revision'), name='unique_diagnostic_record_revision'),
        ),
        migrations.AddIndex(
            model_name='qaevent',
            index=models.Index(fields=['session', 'severity', 'resolved_at'], name='diagnostics_session_4ef025_idx'),
        ),
    ]
