# Generated by Django 5.2.3 on 2026-08-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0007_diagnosticrecord_diagnosticmeasurement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticsession',
            name='status',
            field=models.CharField(choices=[('parse_failed', 'Ошибка обработки отчёта'), ('engine_done', 'Диагностика двигателя завершена'), ('suspension_pending', 'Ожидает осмотра подвески'), ('suspension_done', 'Диагностика подвески завершена')], default='engine_done', max_length=30),
        ),
    ]
