# Generated by Django 5.2.3 on 2026-08-16 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0008_alter_diagnosticsession_status'),
        ('users', '0002_organization_workshop_technicianprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticsession',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_sessions', to='users.organization'),
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_sessions', to='users.workshop'),
        ),
    ]
