# Generated by Django 5.2.3 on 2026-08-16 16:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0009_diagnosticsession_organization_and_more'),
        ('users', '0002_organization_workshop_technicianprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, max_length=64)),
                ('vin_normalized', models.CharField(blank=True, db_index=True, max_length=64)),
                ('make', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('generation', models.CharField(blank=True, max_length=120)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='users.organization')),
            ],
            options={
                'ordering': ['make', 'model', 'vin_normalized'],
            },
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_sessions', to='diagnostics.vehicle'),
        ),
        migrations.CreateModel(
            name='VehicleConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_code', models.CharField(blank=True, max_length=120)),
                ('transmission', models.CharField(blank=True, max_length=120)),
                ('fuel_type', models.CharField(blank=True, max_length=64)),
                ('ecu_hardware', models.CharField(blank=True, max_length=255)),
                ('ecu_software', models.CharField(blank=True, max_length=255)),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True)),
                ('market', models.CharField(blank=True, max_length=64)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_vehicle_configurations', to='users.userprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to='diagnostics.vehicle')),
            ],
            options={
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.AddField(
            model_name='diagnosticsession',
            name='vehicle_configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_sessions', to='diagnostics.vehicleconfiguration'),
        ),
        migrations.CreateModel(
            name='VehicleIdentityObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_data', models.JSONField(default=dict)),
                ('corrections', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('observed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_vehicle_identities', to='users.userprofile')),
                ('parse_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_identity_observations', to='diagnostics.diagnosticparserun')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_identity_observation', to='diagnostics.diagnosticsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('vin_normalized', ''), _negated=True), fields=('organization', 'vin_normalized'), name='unique_vehicle_vin_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='vehicleconfiguration',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('vehicle',), name='unique_current_configuration_per_vehicle'),
        ),
    ]
