# Generated by Django 5.2.3 on 2026-08-16 17:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0010_vehicle_diagnosticsession_vehicle_and_more'),
        ('users', '0002_organization_workshop_technicianprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('intake', 'Intake'), ('identity_pending', 'Vehicle identity pending'), ('ready', 'Ready for diagnostics'), ('in_progress', 'Diagnostics in progress'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], db_index=True, default='intake', max_length=24)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_diagnostic_cases', to='users.userprofile')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_diagnostic_cases', to='users.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_cases', to='users.organization')),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_case', to='diagnostics.diagnosticsession')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='diagnostic_cases', to='users.workshop')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('customer_words', models.TextField(blank=True)),
                ('onset', models.CharField(blank=True, max_length=255)),
                ('frequency', models.CharField(blank=True, max_length=120)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_complaints', to='users.userprofile')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer_complaint', to='diagnostics.diagnosticcase')),
            ],
        ),
        migrations.CreateModel(
            name='OperatingConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('ambient_temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('engine_temperature', models.CharField(blank=True, max_length=64)),
                ('vehicle_speed', models.CharField(blank=True, max_length=64)),
                ('engine_load', models.CharField(blank=True, max_length=64)),
                ('intermittent', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='operating_conditions', to='diagnostics.diagnosticcase')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_operating_conditions', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RecentRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('performed_at', models.DateField(blank=True, null=True)),
                ('mileage_km', models.PositiveIntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recent_repairs', to='diagnostics.diagnosticcase')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_recent_repairs', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('subsystem', models.CharField(blank=True, max_length=120)),
                ('occurrence_conditions', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, max_length=32)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='symptoms', to='diagnostics.diagnosticcase')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_symptoms', to='users.userprofile')),
            ],
        ),
    ]
