# Generated by Django 5.2.3 on 2026-08-16 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0011_diagnosticcase_customercomplaint_operatingconditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='variant',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vehicleconfiguration',
            name='completeness_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete'), ('needs_review', 'Needs review')], db_index=True, default='incomplete', max_length=24),
        ),
        migrations.AddField(
            model_name='vehicleconfiguration',
            name='missing_fields',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vehicleconfiguration',
            name='review_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
