# Generated by Django 5.2.3 on 2026-08-21 19:22

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def link_existing_vehicle_catalog(apps, schema_editor):
    Vehicle = apps.get_model("diagnostics", "Vehicle")
    VehicleBrand = apps.get_model("diagnostics", "VehicleBrand")
    VehicleModel = apps.get_model("diagnostics", "VehicleModel")

    for vehicle in Vehicle.objects.all().iterator():
        make_name = (vehicle.make or "").strip()
        model_name = (vehicle.model or "").strip()
        if not make_name:
            continue

        brand = VehicleBrand.objects.filter(name__iexact=make_name).first()
        if brand is None:
            base_slug = slugify(make_name) or "brand"
            brand_slug = base_slug
            suffix = 2
            while VehicleBrand.objects.filter(slug=brand_slug).exists():
                brand_slug = f"{base_slug}-{suffix}"
                suffix += 1
            brand = VehicleBrand.objects.create(name=make_name, slug=brand_slug)

        vehicle_model = None
        if model_name:
            vehicle_model = VehicleModel.objects.filter(
                brand=brand, name__iexact=model_name
            ).first()
            if vehicle_model is None:
                base_slug = slugify(model_name) or "model"
                model_slug = base_slug
                suffix = 2
                while VehicleModel.objects.filter(
                    brand=brand, slug=model_slug
                ).exists():
                    model_slug = f"{base_slug}-{suffix}"
                    suffix += 1
                vehicle_model = VehicleModel.objects.create(
                    brand=brand, name=model_name, slug=model_slug
                )

        Vehicle.objects.filter(pk=vehicle.pk).update(
            brand=brand, vehicle_model=vehicle_model
        )


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostics', '0012_vehicle_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='diagnostics.vehiclebrand'),
        ),
        migrations.AlterField(
            model_name='diagnosticapproval',
            name='decision',
            field=models.CharField(choices=[('approve', 'Одобрить'), ('reject', 'Отклонить'), ('request_changes', 'Request changes')], max_length=24),
        ),
        migrations.AlterField(
            model_name='diagnosticcase',
            name='status',
            field=models.CharField(choices=[('intake', 'Intake'), ('identity_pending', 'Vehicle identity pending'), ('ready', 'Ready for diagnostics'), ('in_progress', 'В работе'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Закрыто'), ('cancelled', 'Отменено')], db_index=True, default='intake', max_length=24),
        ),
        migrations.AlterField(
            model_name='diagnosticparserun',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('succeeded', 'Успешно'), ('failed', 'Не пройдено')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='diagnosticrecord',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('in_review', 'In review'), ('approved', 'Approved'), ('rejected', 'Отклонено')], db_index=True, default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='dtcreference',
            name='severity',
            field=models.CharField(choices=[('info', 'Информационный'), ('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], default='medium', max_length=32),
        ),
        migrations.AlterField(
            model_name='qaevent',
            name='severity',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Критическая')], db_index=True, default='warning', max_length=16),
        ),
        migrations.AlterField(
            model_name='suspensioninspection',
            name='overall_risk',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='vehicleconfiguration',
            name='completeness_status',
            field=models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Не завершено'), ('needs_review', 'Needs review')], db_index=True, default='incomplete', max_length=24),
        ),
        migrations.AlterField(
            model_name='vehicleidentityobservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='diagnostics.vehiclebrand')),
            ],
            options={
                'verbose_name': 'Модель автомобиля',
                'verbose_name_plural': 'Модели автомобилей',
                'ordering': ['brand__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='diagnostics.vehiclemodel'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('brand', 'name'), name='unique_vehicle_model_name_per_brand'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('brand', 'slug'), name='unique_vehicle_model_slug_per_brand'),
        ),
        migrations.RunPython(link_existing_vehicle_catalog, migrations.RunPython.noop),
    ]
