# Generated by Django 5.2.3 on 2026-08-16 16:26

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.SlugField(max_length=64)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workshops', to='users.organization')),
            ],
            options={
                'ordering': ['organization_id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('service_advisor', 'L0 Service Advisor'), ('junior_technician', 'L1 Junior Technician'), ('diagnostic_technician', 'L2 Diagnostic Technician'), ('senior_expert', 'L3 Senior / Expert'), ('technical_manager', 'Technical Manager'), ('auditor', 'Auditor / Partner')], db_index=True, default='junior_technician', max_length=32)),
                ('employee_id', models.CharField(blank=True, max_length=64)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technicians', to='users.organization')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='technician_profile', to='users.userprofile')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='technicians', to='users.workshop')),
            ],
            options={
                'ordering': ['organization_id', 'user_profile_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='workshop',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_workshop_code_per_organization'),
        ),
        migrations.AddConstraint(
            model_name='technicianprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('employee_id', ''), _negated=True), fields=('organization', 'employee_id'), name='unique_employee_id_per_organization'),
        ),
    ]
