# Generated by Django 5.2.3 on 2026-08-16 18:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostics', '0012_vehicle_variant_and_more'),
        ('users', '0002_organization_workshop_technicianprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100)),
                ('sequence', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('operation_type', models.CharField(choices=[('instruction', 'Instruction'), ('measurement', 'Measurement'), ('diagnostic_scan', 'Diagnostic scan'), ('decision_gate', 'Decision gate'), ('calibration', 'Calibration'), ('road_test', 'Road test'), ('qc', 'Quality control')], default='instruction', max_length=24)),
                ('mandatory', models.BooleanField(default=True)),
                ('blocking', models.BooleanField(default=True)),
                ('qc_operation', models.BooleanField(default=False)),
                ('expected_result', models.TextField(blank=True)),
                ('technical_requirements', models.JSONField(blank=True, default=dict)),
                ('required_tools', models.JSONField(blank=True, default=list)),
                ('specification', models.JSONField(blank=True, default=dict)),
                ('required_skill_level', models.PositiveSmallIntegerField(default=0)),
                ('minimum_role', models.CharField(blank=True, max_length=32)),
                ('approval_required', models.BooleanField(default=False)),
                ('approval_minimum_role', models.CharField(blank=True, max_length=32)),
                ('escalation_allowed', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['version_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='CaseOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', 'Locked'), ('available', 'Available'), ('in_progress', 'In progress'), ('requires_review', 'Requires review'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='locked', max_length=24)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_assurance_operations', to='users.userprofile')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_assurance_operations', to='users.userprofile')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_executions', to='assurance.operation')),
            ],
            options={
                'ordering': ['operation__sequence'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('none', 'None'), ('photo', 'Photo'), ('video', 'Video'), ('text', 'Text'), ('measurement', 'Measurement'), ('diagnostic_scan', 'Diagnostic scan'), ('document', 'Document'), ('confirmation', 'Confirmation')], max_length=24)),
                ('description', models.TextField(blank=True)),
                ('required', models.BooleanField(default=True)),
                ('minimum_count', models.PositiveSmallIntegerField(default=1)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('minimum_value', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('maximum_value', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('metadata_schema', models.JSONField(blank=True, default=dict)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_requirements', to='assurance.operation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcedureVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('retired', 'Retired')], default='draft', max_length=16)),
                ('change_summary', models.TextField(blank=True)),
                ('content_sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_procedure_versions', to='users.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='assurance.procedureversion'),
        ),
        migrations.CreateModel(
            name='ReferenceMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('own', 'Own'), ('service_capture', 'Service capture'), ('youtube_embed', 'YouTube embed'), ('licensed', 'Licensed'), ('oem', 'OEM'), ('external', 'External')], max_length=24)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('provider_asset_id', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('start_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('end_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='assurance/reference/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_media', to='assurance.operation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepairCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('complaint', models.TextField(blank=True)),
                ('initial_state', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('verification', 'Verification'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('verification_status', models.CharField(choices=[('not_run', 'Not run'), ('verified', 'Verified'), ('failed', 'Failed'), ('incomplete', 'Incomplete'), ('requires_review', 'Requires review')], default='not_run', max_length=24)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assurance_repair_cases', to='users.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assurance_repair_cases', to='users.organization')),
                ('procedure_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_cases', to='assurance.procedureversion')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assurance_repair_cases', to='diagnostics.vehicle')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assurance_repair_cases', to='users.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='RepairAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('before_status', models.CharField(blank=True, max_length=32)),
                ('after_status', models.CharField(blank=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assurance_audit_events', to='users.userprofile')),
                ('case_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='assurance.caseoperation')),
                ('repair_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='assurance.repaircase')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExpertDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('rework', 'Rework'), ('escalate', 'Escalate')], max_length=16)),
                ('rationale', models.TextField()),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('case_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expert_decisions', to='assurance.caseoperation')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assurance_expert_decisions', to='users.userprofile')),
                ('repair_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expert_decisions', to='assurance.repaircase')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('none', 'None'), ('photo', 'Photo'), ('video', 'Video'), ('text', 'Text'), ('measurement', 'Measurement'), ('diagnostic_scan', 'Diagnostic scan'), ('document', 'Document'), ('confirmation', 'Confirmation')], max_length=24)),
                ('file', models.FileField(blank=True, null=True, upload_to='assurance/evidence/')),
                ('text', models.TextField(blank=True)),
                ('numeric_value', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True)),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('content_sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('case_operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='assurance.caseoperation')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assurance_evidence', to='users.userprofile')),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='assurance.evidence')),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='assurance.evidencerequirement')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='assurance.operation')),
                ('repair_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='assurance.repaircase')),
            ],
        ),
        migrations.AddField(
            model_name='caseoperation',
            name='repair_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='case_operations', to='assurance.repaircase'),
        ),
        migrations.CreateModel(
            name='RepairCaseTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assurance_assignments_made', to='users.userprofile')),
                ('repair_case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technician_assignments', to='assurance.repaircase')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assurance_case_assignments', to='users.technicianprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RepairProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('vehicle_scope', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_repair_procedures', to='users.userprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_procedures', to='users.organization')),
            ],
        ),
        migrations.AddField(
            model_name='procedureversion',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='assurance.repairprocedure'),
        ),
        migrations.CreateModel(
            name='RepairRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField()),
                ('content_sha256', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repair_case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='repair_record', to='assurance.repaircase')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=160)),
                ('max_level', models.PositiveSmallIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assurance_skills', to='users.organization')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='required_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='assurance.skill'),
        ),
        migrations.CreateModel(
            name='TechnicianSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('verified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='technicians', to='assurance.skill')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assurance_skills', to='users.technicianprofile')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verified_assurance_skills', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_run', 'Not run'), ('verified', 'Verified'), ('failed', 'Failed'), ('incomplete', 'Incomplete'), ('requires_review', 'Requires review')], max_length=24)),
                ('details', models.JSONField(default=dict)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assurance_verifications', to='users.userprofile')),
                ('repair_case', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='verification', to='assurance.repaircase')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertDecisionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_links', to='assurance.expertdecision')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decision_links', to='assurance.evidence')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('decision', 'evidence'), name='unique_assurance_decision_evidence')],
            },
        ),
        migrations.CreateModel(
            name='OperationDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unlocks', to='assurance.operation')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependencies', to='assurance.operation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('operation', 'depends_on'), name='unique_operation_dependency'), models.CheckConstraint(condition=models.Q(('operation', models.F('depends_on')), _negated=True), name='operation_not_self_dependent')],
            },
        ),
        migrations.AddConstraint(
            model_name='caseoperation',
            constraint=models.UniqueConstraint(fields=('repair_case', 'operation'), name='unique_assurance_case_operation'),
        ),
        migrations.AddConstraint(
            model_name='repaircasetechnician',
            constraint=models.UniqueConstraint(fields=('repair_case', 'technician'), name='unique_assurance_case_technician'),
        ),
        migrations.AddConstraint(
            model_name='repairprocedure',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_repair_procedure_code'),
        ),
        migrations.AddConstraint(
            model_name='procedureversion',
            constraint=models.UniqueConstraint(fields=('procedure', 'version'), name='unique_repair_procedure_version'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_assurance_skill_code'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(fields=('version', 'key'), name='unique_operation_key_per_version'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(fields=('version', 'sequence'), name='unique_operation_sequence_per_version'),
        ),
        migrations.AddConstraint(
            model_name='technicianskill',
            constraint=models.UniqueConstraint(fields=('technician', 'skill'), name='unique_assurance_technician_skill'),
        ),
    ]
