# Generated by Django 5.2.3 on 2026-08-16 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verification',
            options={'ordering': ['performed_at', 'id']},
        ),
        migrations.AlterField(
            model_name='verification',
            name='repair_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications', to='assurance.repaircase'),
        ),
    ]
