# Generated by Django 5.2.3 on 2026-08-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0002_alter_verification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertdecision',
            name='authorized_operation_keys',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
