# Generated by Django 5.2.3 on 2026-08-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0003_expertdecision_authorized_operation_keys'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='evidence',
            constraint=models.UniqueConstraint(condition=models.Q(('supersedes__isnull', False)), fields=('supersedes',), name='unique_assurance_evidence_supersession'),
        ),
    ]
