# Generated by Django 5.2.3 on 2026-08-21 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0004_evidence_supersession'),
        ('users', '0002_organization_workshop_technicianprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseOperationException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationale', models.TextField()),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_assurance_exceptions', to='users.userprofile')),
                ('case_operation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='approved_exception', to='assurance.caseoperation')),
            ],
        ),
    ]
