# Generated by Django 5.2.3 on 2026-08-21 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0008_workshop_walkthrough_observation'),
        ('users', '0002_organization_workshop_technicianprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseoperation',
            name='status',
            field=models.CharField(choices=[('locked', 'Недоступно'), ('available', 'Доступно'), ('in_progress', 'В работе'), ('requires_review', 'Требует проверки'), ('completed', 'Завершено'), ('failed', 'Не пройдено'), ('skipped', 'Пропущено')], default='locked', max_length=24),
        ),
        migrations.AlterField(
            model_name='expertdecision',
            name='decision',
            field=models.CharField(choices=[('approve', 'Одобрить'), ('reject', 'Отклонить'), ('rework', 'Вернуть на доработку'), ('escalate', 'Передать эксперту')], max_length=16),
        ),
        migrations.AlterField(
            model_name='expertreviewnotification',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Не пройдено')], db_index=True, default='queued', max_length=16),
        ),
        migrations.AlterField(
            model_name='procedureversion',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликовано'), ('retired', 'Архив')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='repaircase',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В работе'), ('blocked', 'Заблокировано'), ('verification', 'Verification'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='repaircase',
            name='verification_status',
            field=models.CharField(choices=[('not_run', 'Not run'), ('verified', 'Подтверждено'), ('failed', 'Не пройдено'), ('incomplete', 'Не завершено'), ('requires_review', 'Требует проверки')], default='not_run', max_length=24),
        ),
        migrations.AlterField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('not_run', 'Not run'), ('verified', 'Подтверждено'), ('failed', 'Не пройдено'), ('incomplete', 'Не завершено'), ('requires_review', 'Требует проверки')], max_length=24),
        ),
        migrations.AlterField(
            model_name='workshopwalkthroughobservation',
            name='severity',
            field=models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('blocker', 'Blocker')], max_length=12),
        ),
        migrations.CreateModel(
            name='CompetencyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_level', models.PositiveSmallIntegerField()),
                ('decision', models.CharField(choices=[('approve', 'Одобрить'), ('reject', 'Отклонить')], max_length=12)),
                ('rationale', models.TextField()),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competency_reviews_performed', to='users.userprofile')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competency_reviews', to='assurance.skill')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competency_reviews', to='users.technicianprofile')),
            ],
            options={
                'ordering': ['decided_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompetencyReviewEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competency_review_links', to='assurance.evidence')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_links', to='assurance.competencyreview')),
            ],
        ),
        migrations.AddField(
            model_name='competencyreview',
            name='evidence',
            field=models.ManyToManyField(related_name='competency_reviews', through='assurance.CompetencyReviewEvidence', to='assurance.evidence'),
        ),
        migrations.AddConstraint(
            model_name='competencyreviewevidence',
            constraint=models.UniqueConstraint(fields=('review', 'evidence'), name='unique_competency_review_evidence'),
        ),
    ]
