# Generated by Django 5.2.3 on 2025-06-14 08:16

import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryprog',
            options={'ordering': ['id'], 'verbose_name': 'Категория проектов', 'verbose_name_plural': 'Категории проектов'},
        ),
        migrations.AlterModelOptions(
            name='prog',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.RemoveField(
            model_name='prog',
            name='selection_procedure',
        ),
        migrations.RemoveField(
            model_name='prog',
            name='selection_procedure2',
        ),
        migrations.RemoveField(
            model_name='prog',
            name='total_places',
        ),
        migrations.AlterField(
            model_name='prog',
            name='prog_statement',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Положение о проекте'),
        ),
        migrations.AlterField(
            model_name='prog',
            name='prog_statement2',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Положение о проекте 2 абзац'),
        ),
        migrations.AlterField(
            model_name='prog',
            name='registration',
            field=models.ManyToManyField(blank=True, related_name='progs', to=settings.AUTH_USER_MODEL, verbose_name='Участники проекта'),
        ),
        migrations.AlterField(
            model_name='prog',
            name='time_ending',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания проекта'),
        ),
        migrations.AlterField(
            model_name='prog',
            name='time_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала проекта'),
        ),
    ]
