# Generated by Django 5.2.3 on 2025-06-14 08:22

import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_categoryprog_options_alter_prog_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Текст')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='Цена')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото2')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото3')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото4')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото5')),
                ('photo6', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото6')),
                ('time_create', models.DateTimeField(verbose_name='Дата и время создания')),
                ('time_update', models.DateTimeField(verbose_name='Дата и время обновления')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('number_of_employees', models.IntegerField(default=0, max_length=2, verbose_name='Количество сотрудников')),
                ('executor', models.ManyToManyField(blank=True, null=True, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'unique_together': {('title', 'slug')},
            },
        ),
    ]
