# Generated by Django 5.2.3 on 2025-06-14 08:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='executor',
            field=models.ManyToManyField(blank=True, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='service',
            name='number_of_employees',
            field=models.IntegerField(default=0, verbose_name='Количество сотрудников'),
        ),
    ]
