# Generated by Django 5.2.3 on 2026-07-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='generated_source_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Идентификатор внешнего материала'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_topic',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Тема изображения'),
        ),
        migrations.AddField(
            model_name='news',
            name='imported_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Время последнего импорта'),
        ),
        migrations.AddField(
            model_name='news',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='news',
            name='source_note',
            field=models.TextField(blank=True, verbose_name='Примечание об источниках'),
        ),
        migrations.AddField(
            model_name='news',
            name='source_urls',
            field=models.JSONField(blank=True, default=list, verbose_name='Ссылки на источники'),
        ),
    ]
